site_name: Adani Data Platform Documentation
nav:
  - Home: index.md
  - Platform Overview: platform-overview.md
  - Business Systems: business-systems.md
  - Genies: genies.md
  - Data Products: data-products.md
  - Dashboards: dashboards.md
  - Onboarding: onboarding.md
plugins:
  - techdocs-core