apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edl-corp-group-it-prod-budget-variance
  title: Budget Variance (Corp IT - Prod)
  description: 'Budget vs actual across all cost centers and GL accounts.

    Consumers: Finance, Business Heads

    Business: Corp Group IT | Environment: Production'
  tags:
  - data-product
  - prod
  - corp-group-it
  - finance
  - finance
  annotations:
    adani.com/business: edl-corp-group-it
    adani.com/environment: prod
    adani.com/component-type: data-product
    adani.com/sla: Daily by 9 AM IST
  links:
  - url: https://adb-corp-groupit-prod.azuredatabricks.net/explore/data
    title: View in Production Workspace
    icon: dashboard
spec:
  type: data-product
  lifecycle: production
  owner: edl-corp-group-it-team
  system: edl-corp-group-it
  dependsOn:
  - resource:edl-corp-group-it-prod-workspace
