apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bdl-port-dev-berth-occupancy
  title: Berth Occupancy (Port - Dev)
  description: 'Berth occupancy - utilization, idle time, peak hours.

    Consumers: Planning, Port Ops

    Business: Ports and SEZ | Environment: Development'
  tags:
  - data-product
  - dev
  - port
  - logistics
  - planning
  annotations:
    adani.com/business: bdl-port
    adani.com/environment: dev
    adani.com/component-type: data-product
    adani.com/sla: Real-time
  links:
  - url: https://adb-bdl-port-dev.azuredatabricks.net/explore/data
    title: View in Development Workspace
    icon: dashboard
spec:
  type: data-product
  lifecycle: development
  owner: bdl-port-team
  system: bdl-port
  dependsOn:
  - resource:bdl-port-dev-workspace
