apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bdl-hr-dev-compensation-benchmark
  title: Compensation Benchmark (HR - Dev)
  description: 'Internal vs market compensation by role, grade, location.

    Consumers: Comp and Ben Team, CHRO

    Business: Human Resources | Environment: Development'
  tags:
  - data-product
  - dev
  - hr
  - workforce
  - compensation
  annotations:
    adani.com/business: bdl-hr
    adani.com/environment: dev
    adani.com/component-type: data-product
    adani.com/sla: Monthly refresh
  links:
  - url: https://adb-bdl-hr-dev.azuredatabricks.net/explore/data
    title: View in Development Workspace
    icon: dashboard
spec:
  type: data-product
  lifecycle: development
  owner: bdl-hr-team
  system: bdl-hr
  dependsOn:
  - resource:bdl-hr-dev-workspace
