apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edl-corp-group-it-dev-budget-variance
  title: Budget Variance (Corp IT - Dev)
  description: 'Budget vs actual across all cost centers and GL accounts.

    Consumers: Finance, Business Heads

    Business: Corp Group IT | Environment: Development'
  tags:
  - data-product
  - dev
  - corp-group-it
  - finance
  - finance
  annotations:
    adani.com/business: edl-corp-group-it
    adani.com/environment: dev
    adani.com/component-type: data-product
    adani.com/sla: Daily by 9 AM IST
  links:
  - url: https://adb-corp-groupit-dev.azuredatabricks.net/explore/data
    title: View in Development Workspace
    icon: dashboard
spec:
  type: data-product
  lifecycle: development
  owner: edl-corp-group-it-team
  system: edl-corp-group-it
  dependsOn:
  - resource:edl-corp-group-it-dev-workspace
