apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: edl-corp-group-it
  title: EDL - Corp Group IT
  description: |
    Enterprise Data Lake for Corporate Group IT.
    Domains: Finance, Procurement, Compliance, Audit.
    Workspaces: Dev + Prod on Azure Databricks.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/yogeshahuja-dev/adani-data-platform
  tags:
    - edl
    - corp-group-it
    - finance
    - procurement
    - compliance
  links:
    - url: https://adb-corp-groupit-dev.azuredatabricks.net
      title: Dev Workspace
      icon: dashboard
    - url: https://adb-corp-groupit-prod.azuredatabricks.net
      title: Prod Workspace
      icon: dashboard
spec:
  owner: edl-corp-group-it-team